// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderDeliverySystem.Ordering.Infrastructure.Persistence;

#nullable disable

namespace OrderDeliverySystem.Ordering.Infrastructure.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20240728135908_AddedOrderNumberMigrationsd")]
    partial class AddedOrderNumberMigrationsd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Buyers.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BuyerChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyers", "ordering");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderNumber"));

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("OrderStatus", "OrderDeliverySystem.Ordering.Domain.Orders.Order.OrderStatus#OrderStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OrderStatus");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.ToTable("Orders", "ordering");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95cf8c3e-990e-4567-9ff6-f74e90cc23ad"),
                            Address = "123 Main St, Cityville",
                            BuyerId = new Guid("4c024333-a4d1-42c3-a537-0df0dd9946ac"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 28, 13, 59, 8, 238, DateTimeKind.Utc).AddTicks(6560)
                        },
                        new
                        {
                            Id = new Guid("459efc43-e928-412f-a000-d5639ac52826"),
                            Address = "456 Elm St, Townsville",
                            BuyerId = new Guid("4c024333-a4d1-42c3-a537-0df0dd9946ac"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 28, 13, 59, 8, 238, DateTimeKind.Utc).AddTicks(6570)
                        },
                        new
                        {
                            Id = new Guid("1698be4c-0fc6-4eb0-a341-377c6ca9ed5e"),
                            Address = "789 Oak St, Villagetown",
                            BuyerId = new Guid("4c024333-a4d1-42c3-a537-0df0dd9946ac"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 28, 13, 59, 8, 238, DateTimeKind.Utc).AddTicks(6574)
                        },
                        new
                        {
                            Id = new Guid("708a0b4d-8add-45f9-a87c-a3f87c2b9800"),
                            Address = "321 Maple St, Hamletville",
                            BuyerId = new Guid("4c024333-a4d1-42c3-a537-0df0dd9946ac"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 28, 13, 59, 8, 238, DateTimeKind.Utc).AddTicks(6577)
                        });
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("DeliveryOptions", "OrderDeliverySystem.Ordering.Domain.Orders.OrderItem.DeliveryOptions#DeliveryOptions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address");

                            b1.Property<decimal>("DeliveryCost")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DeliveryCost");

                            b1.Property<DateTime>("Deadline")
                                .HasColumnType("datetime2")
                                .HasColumnName("Deadline");

                            b1.Property<string>("DeliveryMethod")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DeliveryMethod");

                            b1.Property<bool>("IsSelfPickup")
                                .HasColumnType("bit")
                                .HasColumnName("IsSelfPickup");
                        });

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "ordering");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.Order", b =>
                {
                    b.HasOne("OrderDeliverySystem.Ordering.Domain.Buyers.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("OrderDeliverySystem.Ordering.Domain.Orders.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
