// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderDeliverySystem.Ordering.Infrastructure.Persistence;

#nullable disable

namespace OrderDeliverySystem.Ordering.Infrastructure.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20240727005701_newBuyerAddedMigration")]
    partial class newBuyerAddedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Buyers.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BuyerChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyers", "ordering");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("OrderStatus", "OrderDeliverySystem.Ordering.Domain.Orders.Order.OrderStatus#OrderStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OrderStatus");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.ToTable("Orders", "ordering");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57ce6d9f-5bd0-4894-a4e2-e8748adf7cb3"),
                            Address = "123 Main St, Cityville",
                            BuyerId = new Guid("df3e4b3a-6704-4691-9b24-469588833b16"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 27, 0, 57, 0, 602, DateTimeKind.Utc).AddTicks(5088)
                        },
                        new
                        {
                            Id = new Guid("e88c7c1a-fe51-4bd2-9dd9-17f1b8fb7a8a"),
                            Address = "456 Elm St, Townsville",
                            BuyerId = new Guid("df3e4b3a-6704-4691-9b24-469588833b16"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 27, 0, 57, 0, 602, DateTimeKind.Utc).AddTicks(5102)
                        },
                        new
                        {
                            Id = new Guid("e95ad8d7-11f6-4940-a841-a8b6f9ca26e1"),
                            Address = "789 Oak St, Villagetown",
                            BuyerId = new Guid("df3e4b3a-6704-4691-9b24-469588833b16"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 27, 0, 57, 0, 602, DateTimeKind.Utc).AddTicks(5105)
                        },
                        new
                        {
                            Id = new Guid("380123b4-fa5f-49e6-a57d-dade94949d40"),
                            Address = "321 Maple St, Hamletville",
                            BuyerId = new Guid("df3e4b3a-6704-4691-9b24-469588833b16"),
                            Description = "The order was submitted",
                            OrderDate = new DateTime(2024, 7, 27, 0, 57, 0, 602, DateTimeKind.Utc).AddTicks(5108)
                        });
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("DeliveryOptions", "OrderDeliverySystem.Ordering.Domain.Orders.OrderItem.DeliveryOptions#DeliveryOptions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address");

                            b1.Property<decimal>("DeliveryCost")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DeliveryCost");

                            b1.Property<DateTime>("DeliveryDateTime")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeliveryDateTime");

                            b1.Property<string>("DeliveryMethod")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DeliveryMethod");

                            b1.Property<bool>("IsSelfPickup")
                                .HasColumnType("bit")
                                .HasColumnName("IsSelfPickup");
                        });

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "ordering");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.Order", b =>
                {
                    b.HasOne("OrderDeliverySystem.Ordering.Domain.Buyers.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("OrderDeliverySystem.Ordering.Domain.Orders.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("OrderDeliverySystem.Ordering.Domain.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
