// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderDeliverySystem.Basket.Infrastructure.Persistence;

#nullable disable

namespace OrderDeliverySystem.Basket.Infrastructure.Migrations
{
    [DbContext(typeof(BasketContext))]
    [Migration("20240806180543_NewOptionItemPropertiIsAdded")]
    partial class NewOptionItemPropertiIsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("basket")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderDeliverySystem.Basket.Domain.Baskets.BasketItem", b =>
                {
                    b.Property<Guid>("BasketItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerBasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeliveryDateTime");

                    b.Property<bool>("IsDelivery")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.ComplexProperty<Dictionary<string, object>>("OptionalItem", "OrderDeliverySystem.Basket.Domain.Baskets.BasketItem.OptionalItem#OptionalItem", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OptionItem_Description");

                            b1.Property<bool>("IsAdded")
                                .HasColumnType("bit")
                                .HasColumnName("IsAdded");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("OptionItem_Name");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("OptionItem_Price");
                        });

                    b.HasKey("BasketItemId");

                    b.HasIndex("CustomerBasketId");

                    b.ToTable("BasketItem", "Basket");
                });

            modelBuilder.Entity("OrderDeliverySystem.Basket.Domain.Baskets.CustomerBasket", b =>
                {
                    b.Property<Guid>("CustomerBasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BuyerChatId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerBasketId");

                    b.ToTable("Basket", "Basket");
                });

            modelBuilder.Entity("OrderDeliverySystem.Basket.Domain.Baskets.BasketItem", b =>
                {
                    b.HasOne("OrderDeliverySystem.Basket.Domain.Baskets.CustomerBasket", "CustomerBasket")
                        .WithMany("Items")
                        .HasForeignKey("CustomerBasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerBasket");
                });

            modelBuilder.Entity("OrderDeliverySystem.Basket.Domain.Baskets.CustomerBasket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
